model BatteryThermalSmooth
  // ── Parameters ──────────────────────────────────────────
  // Battery
  parameter Real C_batt = 20     "Battery thermal capacity [J/K]"
    annotation(Evaluate=false);
  parameter Real R_cond = 1.0    "Internal conduction resistance [K/W]"
    annotation(Evaluate=false);
  parameter Real E_cap  = 3600   "Battery energy capacity [J] (= 1 Wh)"
    annotation(Evaluate=false);

  // Electrical
  parameter Real alpha  = 0.004  "Resistance temperature coefficient [1/K]"
    annotation(Evaluate=false);
  parameter Real T_ref  = 25     "Reference temperature [degC]"
    annotation(Evaluate=false);
  parameter Real V_oc0  = 3.6    "Open circuit voltage coefficients"
    annotation(Evaluate=false);
  parameter Real V_oc1  = 0.5    "  V_oc = V_oc0 + V_oc1*SoC + V_oc2*SoC^2"
    annotation(Evaluate=false);
  parameter Real V_oc2  = -0.2   "  (simple polynomial)"
    annotation(Evaluate=false);
  parameter Real R0   = 0.2    "Internal resistance at T_ref [Ohm]"
    annotation(Evaluate=false);

  // Convection
  parameter Real A_surf = 0.01   "Surface area [m2]"
    annotation(Evaluate=false);
  parameter Real T_amb  = 25     "Ambient temperature [degC]"
    annotation(Evaluate=false);
  parameter Real c_conv = 2  "Convection coefficient [W/(m2·K)]"
    annotation(Evaluate=false);

  // Cooling
  parameter Real Q_cool_max = 10 "Maximum cooling power [W]"
    annotation(Evaluate=false);
  parameter Real T_cool_on  = 37 "Cooling activation threshold [degC]"
    annotation(Evaluate=false);

  parameter Real k_smooth = 5    "Tanh steepness for thermostat smoothing [-]"
    annotation(Evaluate=false);

  // ── Variables ───────────────────────────────────────────
  // States
  Real T_batt(start = 25, fixed = true)  "Battery core temperature [degC]";
  Real SoC(start = 0.2, fixed = true)    "State of charge [0-1]";

  // Electrical
  Real I(start = 1)        "Charging current [A]";
  Real V_term(start = 3.6) "Terminal voltage at the cell clamps [V]";

  // Auxiliary electrical
  Real V_oc     "Open circuit voltage [V]";
  Real R_ohm    "Temperature-dependent internal resistance [Ohm]";
  Real Q_gen    "Heat generated by resistive losses [W]";

  // Auxiliary Thermal
  Real T_surf   "Battery surface temperature [degC]";

  // Named heat flows
  Real Q_cond   "Heat conducted core -> surface [W]";
  Real Q_conv   "Heat convected surface -> ambient [W]";
  Real Q_cool   "Active cooling power removed at surface [W]";

  // Inputs
  input Real P_charge "Commanded charging power [W] (the control the optimiser chooses)";

equation
  // ── Open-circuit voltage: rises with charge level ───────
  V_oc = V_oc0 + V_oc1 * SoC + V_oc2 * SoC^2;

  // ── Internal resistance: rises with temperature ─────────
  R_ohm = R0 * (1 + alpha * (T_batt - T_ref));

  // ── Electrical loop: charging ────────────
  // I = P_charge / V_term;
  // V_term = V_oc - I * R_ohm;

  // Quadratic reformulation
  V_term = V_oc - (P_charge / V_term) * R_ohm;
  I      = P_charge / V_term;

  // ── Heat generation: resistive losses ───────────────
  Q_gen = I^2 * R_ohm;

  // ── Cooling: if-else  ──────
  // if T_batt > T_cool_on then
  //   Q_cool = Q_cool_max;
  // else
  //   Q_cool = 0;
  // end if;

  // ── Cooling: SMOOTH tanh thermostat ────────────
  Q_cool = Q_cool_max * 0.5 * (1 + Modelica.Math.tanh(k_smooth * (T_batt - T_cool_on)));

  // ── Conduction: ───────
  Q_cond = (T_batt - T_surf) / R_cond;

  // ── Passive Convection: surface -> ambient ─────────────
  Q_conv = c_conv * A_surf * (T_surf - T_amb);

  // ── Power balance ───────────
  0 = Q_cond - Q_conv - Q_cool;

  // ── Core energy storage  ───────────
  //    Rate of stored energy = heat generated - heat conducted away
  //    C_batt  "Battery thermal capacity [J/K]"
  C_batt * der(T_batt) = Q_gen - Q_cond;

  // ── Charge  ────────────────
  der(SoC) = P_charge / E_cap;

end BatteryThermalSmooth;
